### ISSUE TITLE
Is 'consistence' an observable property?

### ISSUE THREAD

**Issue by dr-shorthair** [ANZSoilData/def-au-domain#5]
In https://github.com/ANZSoilData/def-au-domain/issues/2#issuecomment-1208903990 @meganrwong asked: 

CONSISTENCE – Not created as high level obsv prop - reasonable not to @dr-shorthair

I’m not sure consistence should be split out – perhaps the following just go under ‘strength’ ‘type’ and ‘degree’

sprop:consistence-strength

sprop:consistence-plasticity-type

sprop:consistence-plasticity-degree

**Comment by dr-shorthair** [comment]
I agree. 'Consistence' is a context, not an observable property. 

(though I must admit I'm confused about what exactly it is)

**Comment by meganrwong** [comment]
'consistence refers to the strength of cohesion and adhesion in the soil' . Since it seems to be a measure of strength, I think strength is the (?) super property? really, you could break these all up as obsv properties 'consistence' 'strength' 'plasticity' 'type' 'degree'. It gets a bit out of hand and confusing knowing what to break out and to what ends.

**Comment by dr-shorthair** [comment]
Maybe pull @ljgregory in on this?

**Comment by meganrwong** [comment]
To be consistent ;) with what we are doing, I found I needed to add consistence. 
so, consistence-stength can be found under 'consistence' and 'strength' 

![image](https://user-images.githubusercontent.com/49380601/184080393-b71e0a66-7ba3-4c7e-8ca2-78eb339d479f.png)

**Comment by dr-shorthair** [comment]
OK - we will take another look later I'm sure ;-)
